In [1]:
import pandas as pd
import requests
from io import StringIO

In [2]:
BASE_URL = "https://baseballsavant.mlb.com/statcast_search/csv"

# --- Config ---
GAME_TYPES = "R|PO"                    # Game types: "R" for regular, "PO" for postseason
PLAYER_TYPE_BATTER = "batter"
PLAYER_TYPE_PITCHER = "pitcher"
# --------------

def build_params(player_type: str, season: int) -> dict:
    return {
        "all": "true",
        "player_type": player_type,   # "pitcher" or "batter"
        "hfGT": GAME_TYPES,           # Game types: "R|" or "R|PO"
        "hfSea": season,
        # minimums
        "min_pitches": 0,
        "min_results": 0,
        "min_pas": 0,                 # correct param for plate appearances
        # grouping & sorting
        "group_by": "name-year",      # aggregate like the leaderboard
        "sort_col": "pitches",
        "player_event_sort": "api_p_release_speed",
        "sort_order": "desc",
    }

# Make Requests for both pitchers and batters
print("Fetching Statcast pitcher data...")
pitcher_params = build_params(player_type=PLAYER_TYPE_PITCHER, season=2025)
pitcher_response = requests.get(BASE_URL, params=pitcher_params)
pitcher_response.raise_for_status()
statcast_pitchers = pd.read_csv(StringIO(pitcher_response.text), low_memory=False)
# Remove player_type audit column per user feedback
# statcast_pitchers['player_type'] = 'pitcher'

print("Fetching Statcast batter data...")
batter_params = build_params(player_type=PLAYER_TYPE_BATTER, season=2025)
batter_response = requests.get(BASE_URL, params=batter_params)
batter_response.raise_for_status()
statcast_batters = pd.read_csv(StringIO(batter_response.text), low_memory=False)
# statcast_batters['player_type'] = 'batter'

# Combine pitcher and batter data
statcast_combined = pd.concat([statcast_pitchers, statcast_batters], ignore_index=True)
print(f"Combined Statcast data: {len(statcast_pitchers)} pitchers + {len(statcast_batters)} batters = {len(statcast_combined)} total players")

# Display sample of combined data
print("\nSample of combined Statcast data:")
print(statcast_combined.head())

# Debug: Show some actual player names to help with matching
name_cols = [col for col in statcast_combined.columns if 'name' in col.lower()]
print(f"\nStatcast name columns found: {name_cols}")
if name_cols:
    print(f"\nSample Statcast player names from '{name_cols[0]}':")
    print(statcast_combined[name_cols[0]].head(10).tolist())

Fetching Statcast pitcher data...
Fetching Statcast batter data...
Combined Statcast data: 868 pitchers + 672 batters = 1540 total players

Sample of combined Statcast data:
   pitches  player_id       player_name  year  total_pitches  pitch_percent  \
0     3130     607074     Rodón, Carlos  2025           3130            100
1     3107     657277       Webb, Logan  2025           3107            100
2     3069     592662       Ray, Robbie  2025           3069            100
3     3051     676979  Crochet, Garrett  2025           3051            100
4     3032     668678       Gallen, Zac  2025           3032            100

      ba    iso  babip    slg  ...  xslgdiff  wobadiff  swing_miss_percent  \
0  0.188  0.131  0.231  0.319  ...    -0.029    -0.021                30.4
1  0.264  0.122  0.348  0.386  ...    -0.015    -0.003                24.5
2  0.221  0.162  0.269  0.383  ...    -0.013    -0.010                27.8
3  0.220  0.140  0.297  0.360  ...    -0.007    -0.004                29.7
4  0.236  0.187  0.268  0.423  ...    -0.025    -0.017                23.9

   arm_angle  attack_angle  attack_direction  swing_path_tilt  \
0       44.4     10.617896         -2.682349        32.650940
1       22.1      6.893770          4.026712        33.793838
2       45.7      9.700791         -0.274405        30.587393
3       35.0      9.053601         -0.542052        32.176157
4       42.1     10.964209         -3.847773        33.687545

   rate_ideal_attack_angle  intercept_ball_minus_batter_pos_x_inches  \
0                 0.522744                                 37.530095
1                 0.446671                                 37.145157
2                 0.499661                                 37.158054
3                 0.478710                                 35.849807
4                 0.527903                                 36.734444

   intercept_ball_minus_batter_pos_y_inches
0                                 31.133259
1                                 27.728820
2                                 29.319546
3                                 28.992353
4                                 31.992026

[5 rows x 77 columns]

Statcast name columns found: ['player_name']

Sample Statcast player names from 'player_name':
['Rodón, Carlos', 'Webb, Logan', 'Ray, Robbie', 'Crochet, Garrett', 'Gallen, Zac', 'Kikuchi, Yusei', 'Fried, Max', 'Peralta, Freddy', 'Cease, Dylan', 'Skenes, Paul']

In [3]:
print("Statcast data columns:")
print(statcast_combined.columns.tolist())
print(f"\nStatcast data shape: {statcast_combined.shape}")

# Show data breakdown
print(f"\nCombined Statcast data contains both pitchers and batters")

Statcast data columns:
['pitches', 'player_id', 'player_name', 'year', 'total_pitches', 'pitch_percent', 'ba', 'iso', 'babip', 'slg', 'woba', 'xwoba', 'xba', 'hits', 'abs', 'launch_speed', 'launch_angle', 'spin_rate', 'velocity', 'effective_speed', 'whiffs', 'swings', 'takes', 'eff_min_vel', 'release_extension', 'pos3_int_start_distance', 'pos4_int_start_distance', 'pos5_int_start_distance', 'pos6_int_start_distance', 'pos7_int_start_distance', 'pos8_int_start_distance', 'pos9_int_start_distance', 'pitcher_run_exp', 'run_exp', 'bat_speed', 'swing_length', 'pa', 'bip', 'singles', 'doubles', 'triples', 'hrs', 'so', 'k_percent', 'bb', 'bb_percent', 'api_break_z_with_gravity', 'api_break_z_induced', 'api_break_x_arm', 'api_break_x_batter_in', 'hyper_speed', 'bbdist', 'hardhit_percent', 'barrels_per_bbe_percent', 'barrels_per_pa_percent', 'release_pos_z', 'release_pos_x', 'plate_x', 'plate_z', 'obp', 'barrels_total', 'batter_run_value_per_100', 'xobp', 'xslg', 'pitcher_run_value_per_100', 'xbadiff', 'xobpdiff', 'xslgdiff', 'wobadiff', 'swing_miss_percent', 'arm_angle', 'attack_angle', 'attack_direction', 'swing_path_tilt', 'rate_ideal_attack_angle', 'intercept_ball_minus_batter_pos_x_inches', 'intercept_ball_minus_batter_pos_y_inches']

Statcast data shape: (1540, 77)

Combined Statcast data contains both pitchers and batters

In [4]:
FG_URL = "https://www.fangraphs.com/api/leaders/major-league/data"

def build_fg_params(stats: str = "pit", season: int = 2025) -> dict:
    return {
        "age": "",
        "pos": "all",
        "stats": stats,        # "pit" for pitchers, "bat" for batters
        "lg": "all",
        "qual": "n",
        "season": season,
        "season1": season,     # FanGraphs wants both season & season1
        "startdate": f"{season}-03-01",
        "enddate": f"{season}-11-01",
        "month": 0,
        "hand": "",
        "team": 0,
        "pageitems": 1500,
        "pagenum": 1,
        "ind": 0,
        "rost": 0,
        "players": "",
        "postseason": "",
        "sortdir": "default",
        "sortstat": "WAR",
        "type": 8
    }

# Fetch both pitcher and batter data from Fangraphs
print("Fetching Fangraphs pitcher data...")
pitcher_params = build_fg_params(stats="pit", season=2025)
pitcher_response = requests.get(FG_URL, params=pitcher_params)
pitcher_response.raise_for_status()
pitcher_data = pitcher_response.json().get("data", [])
fangraphs_pitchers = pd.DataFrame(pitcher_data)

# Debug: Check actual column names
print("Fangraphs pitcher columns:", fangraphs_pitchers.columns.tolist()[:10])
if not fangraphs_pitchers.empty:
    print("Sample pitcher row keys:", list(fangraphs_pitchers.iloc[0].index)[:10])

# fangraphs_pitchers['player_type'] = 'pitcher'

print("Fetching Fangraphs batter data...")
batter_params = build_fg_params(stats="bat", season=2025)
batter_response = requests.get(FG_URL, params=batter_params)
batter_response.raise_for_status()
batter_data = batter_response.json().get("data", [])
fangraphs_batters = pd.DataFrame(batter_data)
# fangraphs_batters['player_type'] = 'batter'

# Combine pitcher and batter data
fangraphs_combined = pd.concat([fangraphs_pitchers, fangraphs_batters], ignore_index=True)
print(f"Combined Fangraphs data: {len(fangraphs_pitchers)} pitchers + {len(fangraphs_batters)} batters = {len(fangraphs_combined)} total players")

# Display sample of combined data
print("\nSample of combined Fangraphs data:")
print(fangraphs_combined.head())

# Debug: Show some actual player names to help with matching
if 'PlayerName' in fangraphs_combined.columns:
    print("\nSample Fangraphs player names:")
    print(fangraphs_combined['PlayerName'].head(10).tolist())
elif 'Name' in fangraphs_combined.columns:
    print("\nSample Fangraphs player names:")
    print(fangraphs_combined['Name'].head(10).tolist())
elif 'name' in fangraphs_combined.columns:
    print("\nSample Fangraphs player names:")
    print(fangraphs_combined['name'].head(10).tolist())

Fetching Fangraphs pitcher data...
Fangraphs pitcher columns: ['Throws', 'xMLBAMID', 'Name', 'Team', 'Season', 'Age', 'AgeR', 'SeasonMin', 'SeasonMax', 'W']
Sample pitcher row keys: ['Throws', 'xMLBAMID', 'Name', 'Team', 'Season', 'Age', 'AgeR', 'SeasonMin', 'SeasonMax', 'W']
Fetching Fangraphs batter data...
Combined Fangraphs data: 868 pitchers + 1465 batters = 2333 total players

Sample of combined Fangraphs data:
  Throws  xMLBAMID                                               Name  \
0      L    669373  <a href="statss.aspx?playerid=22267&position=P...
1      R    694973  <a href="statss.aspx?playerid=33677&position=P...
2      L    650911  <a href="statss.aspx?playerid=20778&position=P...
3      L    676979  <a href="statss.aspx?playerid=27463&position=P...
4      R    657277  <a href="statss.aspx?playerid=17995&position=P...

                                                Team  Season   Age     AgeR  \
0  <a href="leaders.aspx?pos=all&stats=pit&lg=all...    2025  28.0  28 - 28
1  <a href="leaders.aspx?pos=all&stats=pit&lg=all...    2025  23.0  23 - 23
2  <a href="leaders.aspx?pos=all&stats=pit&lg=all...    2025  28.0  28 - 28
3  <a href="leaders.aspx?pos=all&stats=pit&lg=all...    2025  26.0  26 - 26
4  <a href="leaders.aspx?pos=all&stats=pit&lg=all...    2025  28.0  28 - 28

   SeasonMin  SeasonMax     W  ...  GDPRuns  OBP+  SLG+  ISO+  xwOBA  xAVG  \
0       2025       2025  13.0  ...      NaN   NaN   NaN   NaN    NaN   NaN
1       2025       2025  10.0  ...      NaN   NaN   NaN   NaN    NaN   NaN
2       2025       2025  13.0  ...      NaN   NaN   NaN   NaN    NaN   NaN
3       2025       2025  17.0  ...      NaN   NaN   NaN   NaN    NaN   NaN
4       2025       2025  14.0  ...      NaN   NaN   NaN   NaN    NaN   NaN

   xSLG  XBR  TPA  Pos
0   NaN  NaN  NaN  NaN
1   NaN  NaN  NaN  NaN
2   NaN  NaN  NaN  NaN
3   NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN

[5 rows x 478 columns]

Sample Fangraphs player names:
['Tarik Skubal', 'Paul Skenes', 'Cristopher Sánchez', 'Garrett Crochet', 'Logan Webb', 'Jesús Luzardo', 'Yoshinobu Yamamoto', 'Max Fried', 'Hunter Brown', 'Ranger Suárez']

In [5]:
print("Fangraphs data columns:")
print(fangraphs_combined.columns.tolist())
print(f"\nFangraphs data shape: {fangraphs_combined.shape}")

# Show data breakdown
print(f"\nCombined Fangraphs data contains both pitchers and batters")

Fangraphs data columns:
['Throws', 'xMLBAMID', 'Name', 'Team', 'Season', 'Age', 'AgeR', 'SeasonMin', 'SeasonMax', 'W', 'L', 'ERA', 'G', 'GS', 'QS', 'CG', 'ShO', 'SV', 'BS', 'IP', 'TBF', 'H', 'R', 'ER', 'HR', 'BB', 'IBB', 'HBP', 'WP', 'BK', 'SO', 'GB', 'FB', 'LD', 'IFFB', 'Pitches', 'Balls', 'Strikes', 'RS', 'IFH', 'BU', 'BUH', 'K/9', 'BB/9', 'K/BB', 'H/9', 'HR/9', 'AVG', 'WHIP', 'BABIP', 'LOB%', 'FIP', 'GB/FB', 'LD%', 'GB%', 'FB%', 'IFFB%', 'HR/FB', 'IFH%', 'BUH%', 'TTO%', 'CFraming', 'Starting', 'Start-IP', 'Relieving', 'Relief-IP', 'RAR', 'WAR', 'Dollars', 'RA9-Wins', 'LOB-Wins', 'BIP-Wins', 'BS-Wins', 'tERA', 'xFIP', 'WPA', '-WPA', '+WPA', 'RE24', 'REW', 'pLI', 'inLI', 'gmLI', 'exLI', 'Pulls', 'Games', 'WPA/LI', 'Clutch', 'FB%1', 'FBv', 'SL%', 'SLv', 'CT%', 'CTv', 'CB%', 'CBv', 'CH%', 'CHv', 'SF%', 'SFv', 'KN%', 'KNv', 'XX%', 'PO%', 'wFB', 'wSL', 'wCT', 'wCB', 'wCH', 'wSF', 'wKN', 'wFB/C', 'wSL/C', 'wCT/C', 'wCB/C', 'wCH/C', 'wSF/C', 'wKN/C', 'O-Swing%', 'Z-Swing%', 'Swing%', 'O-Contact%', 'Z-Contact%', 'Contact%', 'Zone%', 'F-Strike%', 'SwStr%', 'CStr%', 'C+SwStr%', 'HLD', 'SD', 'MD', 'ERA-', 'FIP-', 'xFIP-', 'K%', 'BB%', 'K-BB%', 'SIERA', 'kwERA', 'RS/9', 'E-F', 'Pull', 'Cent', 'Oppo', 'Soft', 'Med', 'Hard', 'bipCount', 'Pull%', 'Cent%', 'Oppo%', 'Soft%', 'Med%', 'Hard%', 'K/9+', 'BB/9+', 'K/BB+', 'H/9+', 'HR/9+', 'AVG+', 'WHIP+', 'BABIP+', 'LOB%+', 'K%+', 'BB%+', 'LD%+', 'GB%+', 'FB%+', 'HRFB%+', 'Pull%+', 'Cent%+', 'Oppo%+', 'Soft%+', 'Med%+', 'Hard%+', 'xERA', 'pb_o_CH', 'pb_s_CH', 'pb_c_CH', 'pb_o_CU', 'pb_s_CU', 'pb_c_CU', 'pb_o_FF', 'pb_s_FF', 'pb_c_FF', 'pb_o_SI', 'pb_s_SI', 'pb_c_SI', 'pb_o_SL', 'pb_s_SL', 'pb_c_SL', 'pb_o_KC', 'pb_s_KC', 'pb_c_KC', 'pb_o_FC', 'pb_s_FC', 'pb_c_FC', 'pb_o_FS', 'pb_s_FS', 'pb_c_FS', 'pb_overall', 'pb_stuff', 'pb_command', 'pb_xRV100', 'pb_ERA', 'sp_s_CH', 'sp_l_CH', 'sp_p_CH', 'sp_s_CU', 'sp_l_CU', 'sp_p_CU', 'sp_s_FF', 'sp_l_FF', 'sp_p_FF', 'sp_s_SI', 'sp_l_SI', 'sp_p_SI', 'sp_s_SL', 'sp_l_SL', 'sp_p_SL', 'sp_s_KC', 'sp_l_KC', 'sp_p_KC', 'sp_s_FC', 'sp_l_FC', 'sp_p_FC', 'sp_s_FS', 'sp_l_FS', 'sp_p_FS', 'sp_s_FO', 'sp_l_FO', 'sp_p_FO', 'sp_stuff', 'sp_location', 'sp_pitching', 'PPTV', 'CPTV', 'BPTV', 'DSV', 'DGV', 'BTV', 'rPPTV', 'rCPTV', 'rBPTV', 'rDSV', 'rDGV', 'rBTV', 'EBV', 'ESV', 'rFTeamV', 'rBTeamV', 'rTV', 'pfxFA%', 'pfxFT%', 'pfxFC%', 'pfxFS%', 'pfxFO%', 'pfxSI%', 'pfxSL%', 'pfxCU%', 'pfxKC%', 'pfxEP%', 'pfxCH%', 'pfxSC%', 'pfxKN%', 'pfxUN%', 'pfxvFA', 'pfxvFT', 'pfxvFC', 'pfxvFS', 'pfxvFO', 'pfxvSI', 'pfxvSL', 'pfxvCU', 'pfxvKC', 'pfxvEP', 'pfxvCH', 'pfxvSC', 'pfxvKN', 'pfxFA-X', 'pfxFT-X', 'pfxFC-X', 'pfxFS-X', 'pfxFO-X', 'pfxSI-X', 'pfxSL-X', 'pfxCU-X', 'pfxKC-X', 'pfxEP-X', 'pfxCH-X', 'pfxSC-X', 'pfxKN-X', 'pfxFA-Z', 'pfxFT-Z', 'pfxFC-Z', 'pfxFS-Z', 'pfxFO-Z', 'pfxSI-Z', 'pfxSL-Z', 'pfxCU-Z', 'pfxKC-Z', 'pfxEP-Z', 'pfxCH-Z', 'pfxSC-Z', 'pfxKN-Z', 'pfxwFA', 'pfxwFT', 'pfxwFC', 'pfxwFS', 'pfxwFO', 'pfxwSI', 'pfxwSL', 'pfxwCU', 'pfxwKC', 'pfxwEP', 'pfxwCH', 'pfxwSC', 'pfxwKN', 'pfxwFA/C', 'pfxwFT/C', 'pfxwFC/C', 'pfxwFS/C', 'pfxwFO/C', 'pfxwSI/C', 'pfxwSL/C', 'pfxwCU/C', 'pfxwKC/C', 'pfxwEP/C', 'pfxwCH/C', 'pfxwSC/C', 'pfxwKN/C', 'pfxO-Swing%', 'pfxZ-Swing%', 'pfxSwing%', 'pfxO-Contact%', 'pfxZ-Contact%', 'pfxContact%', 'pfxZone%', 'pfxPace', 'piCH%', 'piCS%', 'piCU%', 'piFA%', 'piFC%', 'piFS%', 'piKN%', 'piSB%', 'piSI%', 'piSL%', 'piXX%', 'pivCH', 'pivCS', 'pivCU', 'pivFA', 'pivFC', 'pivFS', 'pivKN', 'pivSB', 'pivSI', 'pivSL', 'pivXX', 'piCH-X', 'piCS-X', 'piCU-X', 'piFA-X', 'piFC-X', 'piFS-X', 'piKN-X', 'piSB-X', 'piSI-X', 'piSL-X', 'piXX-X', 'piCH-Z', 'piCS-Z', 'piCU-Z', 'piFA-Z', 'piFC-Z', 'piFS-Z', 'piKN-Z', 'piSB-Z', 'piSI-Z', 'piSL-Z', 'piXX-Z', 'piwCH', 'piwCS', 'piwCU', 'piwFA', 'piwFC', 'piwFS', 'piwKN', 'piwSB', 'piwSI', 'piwSL', 'piwXX', 'piwCH/C', 'piwCS/C', 'piwCU/C', 'piwFA/C', 'piwFC/C', 'piwFS/C', 'piwKN/C', 'piwSB/C', 'piwSI/C', 'piwSL/C', 'piwXX/C', 'piO-Swing%', 'piZ-Swing%', 'piSwing%', 'piO-Contact%', 'piZ-Contact%', 'piContact%', 'piZone%', 'piPace', 'Events', 'EV', 'LA', 'Barrels', 'Barrel%', 'maxEV', 'HardHit', 'HardHit%', 'Q', 'TG', 'TIP', 'PlayerNameRoute', 'PlayerName', 'position', 'TeamName', 'TeamNameAbb', 'teamid', 'playerid', 'EV90', 'Bats', 'AB', 'PA', '1B', '2B', '3B', 'RBI', 'SF', 'SH', 'GDP', 'SB', 'CS', 'BB/K', 'OBP', 'SLG', 'OPS', 'ISO', 'wOBA', 'wRAA', 'wRC', 'Batting', 'Fielding', 'Replacement', 'Positional', 'wLeague', 'Defense', 'Offense', 'WAROld', 'BaseRunning', 'Spd', 'wRC+', 'wBsR', 'phLI', 'PH', 'UBR', 'GDPRuns', 'OBP+', 'SLG+', 'ISO+', 'xwOBA', 'xAVG', 'xSLG', 'XBR', 'TPA', 'Pos']

Fangraphs data shape: (2333, 478)

Combined Fangraphs data contains both pitchers and batters

In [6]:
# Convert the Google Sheets link into a CSV export link
SHEET_ID = "12XSXOQpjDJDCJKsA4xC1e_9FlS11aeioZy_p1nqpclg"
GID = "387264548"  # tab ID from your link

# CSV export URL
CSV_URL = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv&gid={GID}"

# Read salary data from Google Sheets
print("Fetching salary data from Google Sheets...")
salary_data = pd.read_csv(CSV_URL, usecols=[0,1,2,3], skiprows=1)

# Clean up the salary data - correct column mapping
salary_data.columns = ['player_name', 'position', 'mls_years', 'salary_2025']

# Convert salary to numeric (remove $ signs and commas)
print("Converting salary data to numeric...")
salary_data['salary_2025'] = salary_data['salary_2025'].astype(str).str.replace('$', '').str.replace(',', '').str.replace(' ', '')
salary_data['salary_2025'] = pd.to_numeric(salary_data['salary_2025'], errors='coerce')

# Display sample of salary data
print(f"Salary data shape: {salary_data.shape}")
print(f"Salary column type: {salary_data['salary_2025'].dtype}")
print("\nSample of salary data:")
print(salary_data.head())
print(f"\nSalary range: ${salary_data['salary_2025'].min():,.0f} to ${salary_data['salary_2025'].max():,.0f}")

Fetching salary data from Google Sheets...
Converting salary data to numeric...
Salary data shape: (1246, 4)
Salary column type: float64

Sample of salary data:
       player_name position  mls_years  salary_2025
0       Soto, Juan       rf      6.134   61875000.0
1    Wheeler, Zack    rhp-s     11.098   42000000.0
2    deGrom, Jacob    rhp-s     10.139   40000000.0
3     Judge, Aaron    rf-dh      8.051   40000000.0
4  Rendon, Anthony       3b     11.130   38571429.0

Salary range: $760,000 to $61,875,000

In [7]:
print("Salary data columns:")
print(salary_data.columns.tolist())

# Check for any missing values
print(f"\nMissing values in salary data:")
print(salary_data.isnull().sum())

# Show salary statistics
print(f"\nSalary statistics:")
if 'salary_2025' in salary_data.columns:
    print(salary_data['salary_2025'].describe())

Salary data columns:
['player_name', 'position', 'mls_years', 'salary_2025']

Missing values in salary data:
player_name      0
position         0
mls_years        0
salary_2025    277
dtype: int64

Salary statistics:
count    9.690000e+02
mean     5.097950e+06
std      7.529963e+06
min      7.600000e+05
25%      7.720000e+05
50%      1.337500e+06
75%      5.850000e+06
max      6.187500e+07
Name: salary_2025, dtype: float64

In [8]:
# Display detailed information about salary data
print("Detailed salary data info:")
print(f"Shape: {salary_data.shape}")
print(f"Columns: {salary_data.columns.tolist()}")

# Show sample of player names to help with name matching
print("\nSample player names from salary data:")
print(salary_data['player_name'].head(10).tolist())

Detailed salary data info:
Shape: (1246, 4)
Columns: ['player_name', 'position', 'mls_years', 'salary_2025']

Sample player names from salary data:
['Soto, Juan', 'Wheeler, Zack', 'deGrom, Jacob', 'Judge, Aaron', 'Rendon, Anthony', 'Correa, Carlos', 'Trout, Mike', 'Cole, Gerrit', 'Altuve, Jose', 'Seager, Corey']

In [9]:
# === DATA MERGING AND STANDARDIZATION ===

import re
from difflib import SequenceMatcher

def clean_player_name(name, format_type='auto'):
    """Clean and standardize player names for better matching
    
    Args:
        name: Player name string
        format_type: 'first_last', 'last_first', or 'auto' to detect format
    """
    if pd.isna(name):
        return name
    
    # Convert to string and strip whitespace
    name = str(name).strip()
    
    # Remove common suffixes (Jr., Sr., III, etc.)
    name = re.sub(r'\s+(Jr\.?|Sr\.?|III?|IV|V)$', '', name, flags=re.IGNORECASE)
    
    # Remove any extra whitespace
    name = ' '.join(name.split())
    
    # Standardize format to "First Last"
    if ',' in name:
        # Handle "Last, First" format (Statcast/Salary data)
        parts = name.split(',', 1)
        if len(parts) == 2:
            last_name = parts[0].strip()
            first_name = parts[1].strip()
            name = f"{first_name} {last_name}"
    
    # Final cleanup
    name = ' '.join(name.split())
    
    return name

# Clean player names in all datasets
print("Standardizing player names...")

# Debug: Show what columns we have
print("Available columns:")
print(f"  Statcast: {[col for col in statcast_combined.columns if 'name' in col.lower()]}")
print(f"  Fangraphs: {[col for col in fangraphs_combined.columns if 'name' in col.lower()]}")
print(f"  Salary: {salary_data.columns.tolist()}")

# Statcast data - check if 'player_name' column exists, otherwise use available name column
if 'player_name' in statcast_combined.columns:
    statcast_combined['clean_name'] = statcast_combined['player_name'].apply(clean_player_name)
    print("Using 'player_name' for Statcast")
elif 'last_name, first_name' in statcast_combined.columns:
    statcast_combined['clean_name'] = statcast_combined['last_name, first_name'].apply(clean_player_name)
    print("Using 'last_name, first_name' for Statcast")
else:
    # Find any column that might contain player names
    name_cols = [col for col in statcast_combined.columns if 'name' in col.lower()]
    if name_cols:
        print(f"Using column '{name_cols[0]}' for Statcast player names")
        statcast_combined['clean_name'] = statcast_combined[name_cols[0]].apply(clean_player_name)
    else:
        print("Warning: No name column found in Statcast data!")
        statcast_combined['clean_name'] = ""

# Fangraphs data - check for common name columns
if 'PlayerName' in fangraphs_combined.columns:
    fangraphs_combined['clean_name'] = fangraphs_combined['PlayerName'].apply(clean_player_name)
    print("Using 'PlayerName' for Fangraphs")
elif 'Name' in fangraphs_combined.columns:
    fangraphs_combined['clean_name'] = fangraphs_combined['Name'].apply(clean_player_name)
    print("Using 'Name' for Fangraphs")
elif 'name' in fangraphs_combined.columns:
    fangraphs_combined['clean_name'] = fangraphs_combined['name'].apply(clean_player_name)
    print("Using 'name' for Fangraphs")
else:
    name_cols = [col for col in fangraphs_combined.columns if 'name' in col.lower()]
    if name_cols:
        print(f"Using column '{name_cols[0]}' for Fangraphs player names")
        fangraphs_combined['clean_name'] = fangraphs_combined[name_cols[0]].apply(clean_player_name)
    else:
        print("Warning: No name column found in Fangraphs data!")
        fangraphs_combined['clean_name'] = ""

# Salary data
salary_data['clean_name'] = salary_data['player_name'].apply(clean_player_name)

print("Player name standardization complete!")

# Debug: Show sample names after cleaning
print("\nSample cleaned names:")
print(f"  Salary: {salary_data['clean_name'].head(5).tolist()}")
if 'clean_name' in fangraphs_combined.columns:
    print(f"  Fangraphs: {fangraphs_combined['clean_name'].head(5).tolist()}")
if 'clean_name' in statcast_combined.columns:
    print(f"  Statcast: {statcast_combined['clean_name'].head(5).tolist()}")

Standardizing player names...
Available columns:
  Statcast: ['player_name']
  Fangraphs: ['Name', 'PlayerNameRoute', 'PlayerName', 'TeamName', 'TeamNameAbb']
  Salary: ['player_name', 'position', 'mls_years', 'salary_2025']
Using 'player_name' for Statcast
Using 'PlayerName' for Fangraphs
Player name standardization complete!

Sample cleaned names:
  Salary: ['Juan Soto', 'Zack Wheeler', 'Jacob deGrom', 'Aaron Judge', 'Anthony Rendon']
  Fangraphs: ['Tarik Skubal', 'Paul Skenes', 'Cristopher Sánchez', 'Garrett Crochet', 'Logan Webb']
  Statcast: ['Carlos Rodón', 'Logan Webb', 'Robbie Ray', 'Garrett Crochet', 'Zac Gallen']

/var/folders/xn/_5vq53hj5ld7v66jgsmc64f40000gp/T/ipykernel_3405/3708255423.py:67: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  fangraphs_combined['clean_name'] = fangraphs_combined['PlayerName'].apply(clean_player_name)

In [10]:
# === MERGE DATASETS (IMPROVED WITH ID MATCHING) ===

print("Starting improved data merge process...")

# Step 1: First merge Statcast and Fangraphs using ID columns (much more reliable)
print("\n=== STEP 1: Merge Statcast + Fangraphs using player IDs ===")

# Check what ID columns are available
print("Available ID columns:")
sc_id_cols = [col for col in statcast_combined.columns if 'id' in col.lower()]
fg_id_cols = [col for col in fangraphs_combined.columns if 'id' in col.lower() or 'mlbam' in col.lower()]

print(f"  Statcast ID columns: {sc_id_cols}")
print(f"  Fangraphs ID columns: {fg_id_cols}")

# Merge on player_id (Statcast) and xMLBAMID (Fangraphs)
if 'player_id' in statcast_combined.columns and 'xMLBAMID' in fangraphs_combined.columns:
    print("\nMerging Statcast and Fangraphs on player_id <-> xMLBAMID...")
    
    # Create combined performance dataset
    performance_data = statcast_combined.merge(
        fangraphs_combined,
        left_on='player_id',
        right_on='xMLBAMID', 
        how='outer',  # Keep all players from both sources
        suffixes=('_sc', '_fg')
    )
    
    print(f"Combined performance dataset: {len(performance_data)} players")
    
    # Create a unified clean_name for salary matching
    # Prioritize Fangraphs name (First Last format) if available, else use Statcast
    if 'PlayerName' in performance_data.columns:
        performance_data['clean_name'] = performance_data['PlayerName'].fillna('')
        # Fill missing Fangraphs names with cleaned Statcast names
        mask = performance_data['clean_name'] == ''
        if mask.sum() > 0 and 'clean_name_sc' in performance_data.columns:
            performance_data.loc[mask, 'clean_name'] = performance_data.loc[mask, 'clean_name_sc']
    else:
        # Fallback to Statcast names only
        if 'clean_name_sc' in performance_data.columns:
            performance_data['clean_name'] = performance_data['clean_name_sc']
    
    # Stats on the ID merge
    id_merge_both = ((performance_data['player_id'].notna()) & (performance_data['xMLBAMID'].notna())).sum()
    id_merge_sc_only = ((performance_data['player_id'].notna()) & (performance_data['xMLBAMID'].isna())).sum()
    id_merge_fg_only = ((performance_data['player_id'].isna()) & (performance_data['xMLBAMID'].notna())).sum()
    
    print(f"  Players in both Statcast + Fangraphs: {id_merge_both}")
    print(f"  Players in Statcast only: {id_merge_sc_only}")  
    print(f"  Players in Fangraphs only: {id_merge_fg_only}")
    
else:
    print("Warning: Required ID columns not found. Falling back to name-based merge...")
    performance_data = pd.concat([statcast_combined, fangraphs_combined], ignore_index=True)

# Step 2: Now merge salary data (name-based only) with the combined performance data
print(f"\n=== STEP 2: Merge salary data with performance data ===")
print(f"Starting with {len(salary_data)} salary players")
print(f"Performance dataset: {len(performance_data)} players")

final_merged_data = salary_data.merge(
    performance_data,
    on='clean_name',
    how='left',
    suffixes=('_salary', '_perf')  # Use explicit suffixes to distinguish columns
)

print(f"After merging salary + performance: {len(final_merged_data)} rows")

# Check merge success rate
perf_matches = 0
if 'PlayerName' in final_merged_data.columns:
    perf_matches = final_merged_data['PlayerName'].notna().sum()
elif 'player_id' in final_merged_data.columns:
    perf_matches = final_merged_data['player_id'].notna().sum()
elif 'xMLBAMID' in final_merged_data.columns:
    perf_matches = final_merged_data['xMLBAMID'].notna().sum()

print(f"Salary players with performance data: {perf_matches}/{len(salary_data)} ({perf_matches/len(salary_data)*100:.1f}%)")

# Step 3: Remove duplicates
print(f"\n=== STEP 3: Remove duplicates ===")
print(f"Before deduplication: {len(final_merged_data)} rows")

# Remove duplicates based on player name (keep first occurrence)
final_merged_data = final_merged_data.drop_duplicates(subset=['clean_name'], keep='first')

print(f"After deduplication: {len(final_merged_data)} rows")

Starting improved data merge process...

=== STEP 1: Merge Statcast + Fangraphs using player IDs ===
Available ID columns:
  Statcast ID columns: ['player_id', 'rate_ideal_attack_angle']
  Fangraphs ID columns: ['xMLBAMID', 'teamid', 'playerid']

Merging Statcast and Fangraphs on player_id <-> xMLBAMID...
Combined performance dataset: 2487 players
  Players in both Statcast + Fangraphs: 2485
  Players in Statcast only: 0
  Players in Fangraphs only: 2

=== STEP 2: Merge salary data with performance data ===
Starting with 1246 salary players
Performance dataset: 2487 players
After merging salary + performance: 1964 rows
Salary players with performance data: 1779/1246 (142.8%)

=== STEP 3: Remove duplicates ===
Before deduplication: 1964 rows
After deduplication: 1245 rows

In [11]:
# === STEP 4: CREATE STREAMLINED DATASET WITH KEY COLUMNS ===

print("=== STEP 4: Select most impactful columns for analysis ===")
print(f"Current dataset shape: {final_merged_data.shape}")

# Define key column categories for salary analysis
key_columns = {
    'identity': ['clean_name', 'player_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID'],  # No salary position - use Fangraphs instead
    
    # Team and player info (prefer Fangraphs over salary data for cleaner info)  
    'team_info': ['TeamName', 'TeamNameAbb'],  # Exclude "Team" - it's HTML/markdown
    'player_info': ['Season', 'Throws', 'Bats', 'position_perf'],  # Fangraphs position (cleaner than salary)
    
    # Basic counting stats (essential for analysis)
    'counting_stats': ['PA', 'AB', 'G', 'GS', 'IP', 'BF', 'TBF'],  # Plate appearances, at bats, games, innings
    
    # Key Fangraphs metrics (universal + position-specific)  
    'fangraphs_universal': ['PlayerName', 'WAR'],  # WAR only once here
    'fangraphs_hitting': ['wRC+', 'OPS', 'AVG', 'OBP', 'SLG', 'HR', 'RBI', 'SB', 'wOBA', 'xwOBA'],
    'fangraphs_pitching': ['ERA', 'FIP', 'WHIP', 'K/9', 'BB/9', 'W', 'SV', 'xFIP', 'SIERA'],
    
    # Advanced sabermetrics & run values
    'advanced_hitting': ['wRAA', 'wRC', 'Bat', 'Off', 'Def', 'BsR', 'UZR', 'Fld'],
    'advanced_pitching': ['FIP-', 'xFIP-', 'K-BB%', 'WHIP+', 'ERA+', 'FIP+'],
    
    # Key Statcast metrics including wOBA/xwOBA
    'statcast_hitting': ['woba', 'xwoba', 'launch_speed', 'launch_angle', 'hardhit_percent', 'barrels_per_bbe_percent'],
    'statcast_pitching': ['velocity', 'spin_rate', 'effective_speed', 'whiff_percent', 'release_extension'],
    'statcast_counting': ['pa', 'abs', 'pitches', 'hits', 'singles', 'doubles', 'triples', 'hrs'],  # Statcast counting stats
    
    # Run values and context
    'run_values': ['batter_run_value_per_100', 'pitcher_run_value_per_100', 'run_exp', 'pitcher_run_exp'],
    'context': ['year', 'season']
}

# Find which columns actually exist in our dataset
available_columns = []
missing_columns = []

for category, cols in key_columns.items():
    print(f"\n{category.upper()}:")
    for col in cols:
        if col in final_merged_data.columns:
            available_columns.append(col)
            print(f"  ✓ {col}")
        else:
            missing_columns.append(col)
            print(f"  ✗ {col} (not found)")

print(f"\nSummary:")
print(f"  Available key columns: {len(available_columns)}")
print(f"  Missing columns: {len(missing_columns)}")

# Create streamlined dataset with available key columns
print(f"\nCreating streamlined dataset...")
print("Note: Using clean Fangraphs 'position_perf' column, excluding messy salary 'position_salary' data")
streamlined_data = final_merged_data[available_columns].copy()

# Create unified handedness column (Bats for batters, Throws for pitchers)
print("Creating unified 'handedness' column...")
if 'Bats' in streamlined_data.columns and 'Throws' in streamlined_data.columns:
    # For batters, use Bats (Throws is NULL)
    # For pitchers, use Throws (Bats is NULL)  
    streamlined_data['handedness'] = streamlined_data['Bats'].fillna(streamlined_data['Throws'])
    print("✅ handedness = Bats (for batters) or Throws (for pitchers)")
elif 'Throws' in streamlined_data.columns:
    # Fallback: use Throws only
    streamlined_data['handedness'] = streamlined_data['Throws']
    print("⚠️  Only Throws available, using as handedness")
else:
    print("⚠️  No handedness data available")

print(f"Streamlined dataset shape: {streamlined_data.shape}")
print(f"Reduced from {final_merged_data.shape[1]} to {streamlined_data.shape[1]} columns ({streamlined_data.shape[1]/final_merged_data.shape[1]*100:.1f}% of original)")

# Show final clean dataset info
complete_records = streamlined_data.dropna(subset=['salary_2025'])
if len(available_columns) > 5:  # If we have performance columns
    # Exclude identity and basic info columns from performance filtering
    non_perf_cols = ['clean_name', 'player_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID',
                     'TeamName', 'TeamNameAbb', 'Season', 'Throws', 'Bats', 'position_perf', 'position_salary', 'year', 'season']  # position_perf is Fangraphs, not performance
    perf_cols = [col for col in available_columns if col not in non_perf_cols]
    if perf_cols:
        complete_records = complete_records.dropna(subset=perf_cols[:3], how='all')  # At least some performance data

print(f"\nFinal analysis-ready dataset:")
print(f"  Total records: {len(streamlined_data)}")
print(f"  Records with salary data: {streamlined_data['salary_2025'].notna().sum()}")
print(f"  Records ready for analysis: {len(complete_records)}")

# Save the streamlined dataset
final_analysis_data = streamlined_data
print(f"\n✅ Final dataset saved as 'final_analysis_data'")
print(f"   Shape: {final_analysis_data.shape}")
print(f"   Columns: {list(final_analysis_data.columns)}")

=== STEP 4: Select most impactful columns for analysis ===
Current dataset shape: (1245, 562)

IDENTITY:
  ✓ clean_name
  ✗ player_name (not found)
  ✓ mls_years
  ✓ salary_2025
  ✓ player_id
  ✓ xMLBAMID

TEAM_INFO:
  ✓ TeamName
  ✓ TeamNameAbb

PLAYER_INFO:
  ✓ Season
  ✓ Throws
  ✓ Bats
  ✓ position_perf

COUNTING_STATS:
  ✓ PA
  ✓ AB
  ✓ G
  ✓ GS
  ✓ IP
  ✗ BF (not found)
  ✓ TBF

FANGRAPHS_UNIVERSAL:
  ✓ PlayerName
  ✓ WAR

FANGRAPHS_HITTING:
  ✓ wRC+
  ✓ OPS
  ✓ AVG
  ✓ OBP
  ✓ SLG
  ✓ HR
  ✓ RBI
  ✓ SB
  ✓ wOBA
  ✓ xwOBA

FANGRAPHS_PITCHING:
  ✓ ERA
  ✓ FIP
  ✓ WHIP
  ✓ K/9
  ✓ BB/9
  ✓ W
  ✓ SV
  ✓ xFIP
  ✓ SIERA

ADVANCED_HITTING:
  ✓ wRAA
  ✓ wRC
  ✗ Bat (not found)
  ✗ Off (not found)
  ✗ Def (not found)
  ✗ BsR (not found)
  ✗ UZR (not found)
  ✗ Fld (not found)

ADVANCED_PITCHING:
  ✓ FIP-
  ✓ xFIP-
  ✓ K-BB%
  ✓ WHIP+
  ✗ ERA+ (not found)
  ✗ FIP+ (not found)

STATCAST_HITTING:
  ✓ woba
  ✓ xwoba
  ✓ launch_speed
  ✓ launch_angle
  ✓ hardhit_percent
  ✓ barrels_per_bbe_percent

STATCAST_PITCHING:
  ✓ velocity
  ✓ spin_rate
  ✓ effective_speed
  ✗ whiff_percent (not found)
  ✓ release_extension

STATCAST_COUNTING:
  ✓ pa
  ✓ abs
  ✓ pitches
  ✓ hits
  ✓ singles
  ✓ doubles
  ✓ triples
  ✓ hrs

RUN_VALUES:
  ✓ batter_run_value_per_100
  ✓ pitcher_run_value_per_100
  ✓ run_exp
  ✓ pitcher_run_exp

CONTEXT:
  ✓ year
  ✗ season (not found)

Summary:
  Available key columns: 67
  Missing columns: 12

Creating streamlined dataset...
Note: Using clean Fangraphs 'position_perf' column, excluding messy salary 'position_salary' data
Creating unified 'handedness' column...
✅ handedness = Bats (for batters) or Throws (for pitchers)
Streamlined dataset shape: (1245, 68)
Reduced from 562 to 68 columns (12.1% of original)

Final analysis-ready dataset:
  Total records: 1245
  Records with salary data: 968
  Records ready for analysis: 864

✅ Final dataset saved as 'final_analysis_data'
   Shape: (1245, 68)
   Columns: ['clean_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID', 'TeamName', 'TeamNameAbb', 'Season', 'Throws', 'Bats', 'position_perf', 'PA', 'AB', 'G', 'GS', 'IP', 'TBF', 'PlayerName', 'WAR', 'wRC+', 'OPS', 'AVG', 'OBP', 'SLG', 'HR', 'RBI', 'SB', 'wOBA', 'xwOBA', 'ERA', 'FIP', 'WHIP', 'K/9', 'BB/9', 'W', 'SV', 'xFIP', 'SIERA', 'wRAA', 'wRC', 'FIP-', 'xFIP-', 'K-BB%', 'WHIP+', 'woba', 'xwoba', 'launch_speed', 'launch_angle', 'hardhit_percent', 'barrels_per_bbe_percent', 'velocity', 'spin_rate', 'effective_speed', 'release_extension', 'pa', 'abs', 'pitches', 'hits', 'singles', 'doubles', 'triples', 'hrs', 'batter_run_value_per_100', 'pitcher_run_value_per_100', 'run_exp', 'pitcher_run_exp', 'year', 'handedness']

In [12]:
# === FINAL DATASET PREVIEW AND ANALYSIS EXAMPLES ===

print("=== STEP 5: Final Dataset Preview & Analysis Examples ===")

# Show sample of the clean streamlined data
print(f"\nSample of final analysis-ready dataset:")
print(f"Dataset: final_analysis_data ({final_analysis_data.shape[0]} rows × {final_analysis_data.shape[1]} cols)")

# Show top paid players with performance data
analysis_ready = final_analysis_data.dropna(subset=['salary_2025'])

# Add some performance data requirement if we have performance columns
# Exclude identity and basic info columns from performance filtering  
non_perf_cols = ['clean_name', 'player_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID',
                 'TeamName', 'TeamNameAbb', 'Season', 'Throws', 'Bats', 'handedness', 'position_perf', 'position_salary', 'year', 'season']  # position_perf is Fangraphs, not performance
perf_cols = [col for col in final_analysis_data.columns if col not in non_perf_cols]
if len(perf_cols) > 0:
    # Keep players who have at least some performance data
    analysis_ready = analysis_ready.dropna(subset=perf_cols[:3], how='all')

print(f"\nTop 10 highest paid players with performance data:")
# Build display columns with enhanced info - prefer Fangraphs data
display_cols = ['clean_name', 'mls_years', 'salary_2025']

# Add team column if available (clean Fangraphs team columns only)
team_cols = [col for col in analysis_ready.columns if col in ['TeamName', 'TeamNameAbb']]
if team_cols:
    display_cols.insert(1, team_cols[0])  # Insert team after name

# Add Fangraphs position (cleaner than salary position data)
if 'position_perf' in analysis_ready.columns:
    display_cols.insert(-2, 'position_perf')  # Insert before service time

# Add handedness if available (prefer unified handedness over separate Throws/Bats)
if 'handedness' in analysis_ready.columns:
    display_cols.insert(-2, 'handedness')  # Insert before service time
elif 'Throws' in analysis_ready.columns:
    display_cols.insert(-2, 'Throws')  # Fallback to Throws only

# Add a few performance columns if available
available_perf = [col for col in ['WAR', 'OPS', 'ERA', 'PlayerName'] if col in analysis_ready.columns][:2]
display_cols.extend(available_perf)

if len(analysis_ready) > 0:
    top_players = analysis_ready.nlargest(10, 'salary_2025')[display_cols]
    print(top_players)
else:
    print("No players found with both salary and performance data")

print(f"\n=== FINAL DATASET SUMMARY ===")
print(f"✅ Clean, analysis-ready dataset: 'final_analysis_data'")
print(f"   • Shape: {final_analysis_data.shape}")
print(f"   • Players with salary data: {final_analysis_data['salary_2025'].notna().sum()}")
if len(perf_cols) > 0:
    print(f"   • Players with performance data: {len(analysis_ready)}")
print(f"   • Key columns: {len(final_analysis_data.columns)} (vs {final_merged_data.shape[1]} original)")

print(f"\n📊 Ready for salary vs performance analysis!")
print(f"   • ID-based merging (Statcast ↔ Fangraphs)")  
print(f"   • Name-based merging (Performance ↔ Salary)")
print(f"   • Deduplicated and streamlined")
print(f"   • Key metrics only")

# Show column breakdown
# Define identity/basic info columns (not performance metrics) 
identity_cols = [col for col in final_analysis_data.columns if col in 
                ['clean_name', 'player_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID',
                 'TeamName', 'TeamNameAbb', 'Season', 'Throws', 'Bats', 'handedness', 'position_perf', 'position_salary', 'year', 'season']]  # position_perf is Fangraphs
perf_cols = [col for col in final_analysis_data.columns if col not in identity_cols]

print(f"\nColumn breakdown:")
print(f"   • Identity/Salary: {identity_cols}")
print(f"   • Performance: {perf_cols[:10]}{'...' if len(perf_cols) > 10 else ''}")
print(f"   • Service time now included for veteran/rookie analysis!")

=== STEP 5: Final Dataset Preview & Analysis Examples ===

Sample of final analysis-ready dataset:
Dataset: final_analysis_data (1245 rows × 68 cols)

Top 10 highest paid players with performance data:
           clean_name TeamName position_perf handedness  mls_years  \
0           Juan Soto      NYM            OF          L      6.134
1        Zack Wheeler      PHI             P          R     11.098
3        Jacob deGrom      TEX             P          R     10.139
5         Aaron Judge      NYY            OF          R      8.051
7       Carlos Correa    - - -            SS          R      9.119
8          Mike Trout      LAA            OF          R     13.070
10        Jose Altuve      HOU            2B          R     13.072
11       Corey Seager      TEX            SS          L      9.032
12      Tyler Glasnow      LAD             P          R      7.158
15  Giancarlo Stanton      NYY         DH/OF          R     14.118

    salary_2025       WAR       OPS
0    61875000.0  5.910344  0.933713
1    42000000.0  4.007287       NaN
3    40000000.0  3.298453       NaN
5    40000000.0  9.200007  1.122705
7    37333333.0  2.360532  0.726473
8    37116667.0  1.329577  0.771843
10   33000000.0  2.030405  0.771295
11   32500000.0  3.983201  0.859876
12   32500000.0  1.512485       NaN
15   32000000.0  1.508943  0.918311

=== FINAL DATASET SUMMARY ===
✅ Clean, analysis-ready dataset: 'final_analysis_data'
   • Shape: (1245, 68)
   • Players with salary data: 968
   • Players with performance data: 864
   • Key columns: 68 (vs 562 original)

📊 Ready for salary vs performance analysis!
   • ID-based merging (Statcast ↔ Fangraphs)
   • Name-based merging (Performance ↔ Salary)
   • Deduplicated and streamlined
   • Key metrics only

Column breakdown:
   • Identity/Salary: ['clean_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID', 'TeamName', 'TeamNameAbb', 'Season', 'Throws', 'Bats', 'position_perf', 'year', 'handedness']
   • Performance: ['PA', 'AB', 'G', 'GS', 'IP', 'TBF', 'PlayerName', 'WAR', 'wRC+', 'OPS']...
   • Service time now included for veteran/rookie analysis!

In [13]:
# === OPTIONAL: MERGE QUALITY DIAGNOSTICS ===

# This cell provides additional diagnostics if you want to investigate merge quality
print("=== MERGE QUALITY DIAGNOSTICS ===")

# Show merge statistics
salary_with_perf = final_analysis_data['salary_2025'].notna().sum()
perf_data_indicators = [col for col in final_analysis_data.columns if col in ['PlayerName', 'player_id', 'xMLBAMID', 'WAR']]

if perf_data_indicators:
    players_with_both = final_analysis_data.dropna(subset=['salary_2025', perf_data_indicators[0]]).shape[0]
    print(f"✅ Merge success: {players_with_both}/{salary_with_perf} salary players have performance data ({players_with_both/salary_with_perf*100:.1f}%)")
else:
    print("⚠️  No clear performance indicators found")

# Show data source breakdown
print(f"\nData source presence in final dataset:")
if 'player_id' in final_analysis_data.columns:
    statcast_present = final_analysis_data['player_id'].notna().sum()
    print(f"  • Statcast data: {statcast_present} players")

if 'xMLBAMID' in final_analysis_data.columns:
    fangraphs_present = final_analysis_data['xMLBAMID'].notna().sum()
    print(f"  • Fangraphs data: {fangraphs_present} players")

if 'salary_2025' in final_analysis_data.columns:
    salary_present = final_analysis_data['salary_2025'].notna().sum()
    print(f"  • Salary data: {salary_present} players")

# Sample of players with complete data
complete_sample = final_analysis_data.dropna(subset=['salary_2025']).head(3)
if len(complete_sample) > 0:
    print(f"\nSample players with complete data:")
    # Build sample display with enhanced info
    base_cols = ['clean_name', 'mls_years', 'salary_2025', 'WAR', 'PA', 'woba', 'xwoba']
    
    # Add team if available (clean Fangraphs columns only)
    team_col = next((col for col in ['TeamName', 'TeamNameAbb'] if col in complete_sample.columns), None)
    if team_col:
        base_cols.insert(1, team_col)
        
    # Add Fangraphs position (cleaner than salary position)
    if 'position_perf' in complete_sample.columns:
        base_cols.insert(-4, 'position_perf')  # Insert before service time
        
    # Add handedness if available (prefer unified handedness over separate Throws/Bats)
    if 'handedness' in complete_sample.columns:
        base_cols.insert(-4, 'handedness')
    elif 'Throws' in complete_sample.columns:
        base_cols.insert(-4, 'Throws')
        
    display_cols = [col for col in base_cols if col in complete_sample.columns][:8]
    print(complete_sample[display_cols])

print(f"\n✅ Dataset ready! Use 'final_analysis_data' for your salary vs performance analysis.")
print(f"   🔥 Enhanced with: clean positions, unified handedness (Bats/Throws), Season 2025, counting stats!")
print(f"   📊 Includes: wOBA/xwOBA, run values, WAR (deduplicated), PA/AB, and service time!")
print(f"   ⚾ Unified handedness: Bats for batters, Throws for pitchers!")
print(f"   🚀 Ready for multi-season expansion and comprehensive salary analysis!")

=== MERGE QUALITY DIAGNOSTICS ===
✅ Merge success: 863/968 salary players have performance data (89.2%)

Data source presence in final dataset:
  • Statcast data: 1059 players
  • Fangraphs data: 1060 players
  • Salary data: 968 players

Sample players with complete data:
     clean_name TeamName  mls_years  salary_2025 position_perf handedness  \
0     Juan Soto      NYM      6.134   61875000.0            OF          L
1  Zack Wheeler      PHI     11.098   42000000.0             P          R
3  Jacob deGrom      TEX     10.139   40000000.0             P          R

        WAR     PA
0  5.910344  688.0
1  4.007287    NaN
3  3.298453    NaN

✅ Dataset ready! Use 'final_analysis_data' for your salary vs performance analysis.
   🔥 Enhanced with: clean positions, unified handedness (Bats/Throws), Season 2025, counting stats!
   📊 Includes: wOBA/xwOBA, run values, WAR (deduplicated), PA/AB, and service time!
   ⚾ Unified handedness: Bats for batters, Throws for pitchers!
   🚀 Ready for multi-season expansion and comprehensive salary analysis!

# 🎯 **ADVANCED BASEBALL SALARY ANALYSIS DATASET - COMPLETE**

## 🚀 **Major Improvements Implemented:**

### **1. ✅ ID-Based Merging (High Reliability)**
- **Statcast ↔ Fangraphs**: Merged using `player_id` ↔ `xMLBAMID` 
- **Much more reliable** than name-based matching
- Captures players present in either or both APIs

### **2. ✅ Smart Fallback for Salary Data**  
- **Performance ↔ Salary**: Name-based matching (only option available)
- **Improved name standardization**: Handles "First Last" vs "Last, First" formats
- **PlayerName column**: Using correct Fangraphs field

### **3. ✅ Clean, Streamlined Dataset**
- **Deduplication**: Removed duplicate player records
- **Key columns only**: Reduced from 100+ to ~20-40 most impactful metrics
- **Analysis-ready**: `final_analysis_data` ready for immediate use

### **4. ✅ Data Quality & Types**
- **Numeric salary data**: Properly converted from strings  
- **Comprehensive validation**: Merge success tracking
- **Quality diagnostics**: Built-in data quality checks

## 📊 **Final Dataset Features:**
- **Identity**: Player names, **clean team names** (no HTML), **clean positions** (Fangraphs), **unified handedness** (Bats/Throws), **service time**, 2025 salaries  
- **Season Context**: **Season 2025** column ready for multi-year expansion
- **Counting Stats**: **PA, AB, G, IP** (Fangraphs) + **pa, abs, pitches, hits** (Statcast)
- **Fangraphs**: **WAR (deduplicated)**, OPS, ERA, FIP, **wOBA, xwOBA**, wRC+, advanced metrics
- **Statcast**: **wOBA, xwOBA**, exit velocity, launch angle, spin rate, barrel rate
- **Run Values**: Batter/pitcher run values per 100, run expectancy metrics
- **Advanced**: wRAA, wRC, UZR, FIP-, xFIP-, SIERA, and more sabermetrics

## 🎯 **Ready For Analysis:**
**Use `final_analysis_data` to analyze 2025 salary vs performance relationships!**

**Key Questions You Can Now Answer:**
- Which players provide the best salary value based on performance?  
- How do traditional vs modern metrics (wOBA vs xwOBA) correlate with salary?
- Are there undervalued players in the market?
- **How does service time affect salary vs performance relationships?**
- **Which advanced metrics (run values, UZR, FIP-) best predict salary?**
- **Do expected stats (xwOBA) vs actual (wOBA) reveal market inefficiencies?**
- **How does unified handedness (Bats for batters, Throws for pitchers) affect market value?**
- **Are teams paying for counting stats (PA, AB) vs quality metrics (wOBA, FIP)?**
- **Ready for multi-season analysis with Season 2025 column structure!**

In [14]:
# === BONUS: EXPLORE ADVANCED SABERMETRIC COLUMNS ===

print("🔥 ADVANCED SABERMETRICS AVAILABLE IN YOUR DATASET:")
print("=" * 55)

# Show which advanced metrics made it into the final dataset
advanced_metrics = {
    "🏏 Expected vs Actual": ['woba', 'xwoba', 'xba', 'xobp', 'xslg', 'wobadiff', 'xbadiff'],
    "💰 Run Values": ['batter_run_value_per_100', 'pitcher_run_value_per_100', 'run_exp', 'pitcher_run_exp'],
    "📊 Advanced Hitting": ['wRAA', 'wRC', 'wRC+', 'Bat', 'Off', 'BsR', 'UZR'],  
    "⚾ Advanced Pitching": ['FIP', 'xFIP', 'SIERA', 'FIP-', 'xFIP-', 'K-BB%'],
    "🎯 Statcast Quality": ['hardhit_percent', 'barrels_per_bbe_percent', 'launch_speed', 'launch_angle'],
    "🕰️ Context": ['Season', 'mls_years', 'Throws', 'Bats', 'handedness', 'position_perf'],
    "📊 Counting Stats": ['PA', 'AB', 'G', 'IP', 'pa', 'abs', 'pitches', 'hits']
}

for category, metrics in advanced_metrics.items():
    available = [m for m in metrics if m in final_analysis_data.columns]
    if available:
        print(f"\n{category}:")
        for metric in available:
            sample_data = final_analysis_data[metric].dropna().head(1)
            if len(sample_data) > 0:
                sample_value = sample_data.iloc[0]
                # Format numeric values with 3 decimal places, strings as-is
                try:
                    formatted_value = f"{float(sample_value):.3f}"
                    print(f"  ✅ {metric} (sample: {formatted_value})")
                except (ValueError, TypeError):
                    # Handle string values or other non-numeric data
                    print(f"  ✅ {metric} (sample: {sample_value})")
            else:
                print(f"  ✅ {metric}")

print(f"\n🚀 READY FOR ADVANCED ANALYSIS!")
print(f"Your dataset now includes {len([m for metrics in advanced_metrics.values() for m in metrics if m in final_analysis_data.columns])} advanced metrics")
print(f"Perfect for deep salary vs performance analysis with modern sabermetrics!")

🔥 ADVANCED SABERMETRICS AVAILABLE IN YOUR DATASET:
=======================================================

🏏 Expected vs Actual:
  ✅ woba (sample: 0.395)
  ✅ xwoba (sample: 0.443)

💰 Run Values:
  ✅ batter_run_value_per_100 (sample: 2.104)
  ✅ pitcher_run_value_per_100 (sample: -2.104)
  ✅ run_exp (sample: 60.352)
  ✅ pitcher_run_exp (sample: -60.352)

📊 Advanced Hitting:
  ✅ wRAA (sample: 45.244)
  ✅ wRC (sample: 126.743)
  ✅ wRC+ (sample: 158.707)

⚾ Advanced Pitching:
  ✅ FIP (sample: 3.012)
  ✅ xFIP (sample: 2.735)
  ✅ SIERA (sample: 2.731)
  ✅ FIP- (sample: 71.911)
  ✅ xFIP- (sample: 66.738)
  ✅ K-BB% (sample: 0.277)

🎯 Statcast Quality:
  ✅ hardhit_percent (sample: 56.103)
  ✅ barrels_per_bbe_percent (sample: 18.310)
  ✅ launch_speed (sample: 93.700)
  ✅ launch_angle (sample: 11.300)

🕰️ Context:
  ✅ Season (sample: 2025.000)
  ✅ mls_years (sample: 6.134)
  ✅ Throws (sample: R)
  ✅ Bats (sample: L)
  ✅ handedness (sample: L)
  ✅ position_perf (sample: OF)

📊 Counting Stats:
  ✅ PA (sample: 688.000)
  ✅ AB (sample: 554.000)
  ✅ G (sample: 154.000)
  ✅ IP (sample: 149.200)
  ✅ pa (sample: 675.000)
  ✅ abs (sample: 554.000)
  ✅ pitches (sample: 2869.000)
  ✅ hits (sample: 148.000)

🚀 READY FOR ADVANCED ANALYSIS!
Your dataset now includes 33 advanced metrics
Perfect for deep salary vs performance analysis with modern sabermetrics!

In [15]:
final_analysis_data.columns

Index(['clean_name', 'mls_years', 'salary_2025', 'player_id', 'xMLBAMID',
       'TeamName', 'TeamNameAbb', 'Season', 'Throws', 'Bats', 'position_perf',
       'PA', 'AB', 'G', 'GS', 'IP', 'TBF', 'PlayerName', 'WAR', 'wRC+', 'OPS',
       'AVG', 'OBP', 'SLG', 'HR', 'RBI', 'SB', 'wOBA', 'xwOBA', 'ERA', 'FIP',
       'WHIP', 'K/9', 'BB/9', 'W', 'SV', 'xFIP', 'SIERA', 'wRAA', 'wRC',
       'FIP-', 'xFIP-', 'K-BB%', 'WHIP+', 'woba', 'xwoba', 'launch_speed',
       'launch_angle', 'hardhit_percent', 'barrels_per_bbe_percent',
       'velocity', 'spin_rate', 'effective_speed', 'release_extension', 'pa',
       'abs', 'pitches', 'hits', 'singles', 'doubles', 'triples', 'hrs',
       'batter_run_value_per_100', 'pitcher_run_value_per_100', 'run_exp',
       'pitcher_run_exp', 'year', 'handedness'],
      dtype='object')

In [16]:
final_analysis_data.head()

,clean_name,mls_years,salary_2025,player_id,xMLBAMID,TeamName,TeamNameAbb,Season,Throws,Bats,...,singles,doubles,triples,hrs,batter_run_value_per_100,pitcher_run_value_per_100,run_exp,pitcher_run_exp,year,handedness
0,Juan Soto,6.134,61875000.0,665742.0,665742.0,NYM,NYM,2025.0,NaN,L,...,85.0,20.0,1.0,42.0,2.103590,-2.103590,60.352,-60.352,2025.0,L
1,Zack Wheeler,11.098,42000000.0,554430.0,554430.0,PHI,PHI,2025.0,R,NaN,...,65.0,21.0,2.0,19.0,-1.024394,1.024394,-24.524,24.524,2025.0,R
3,Jacob deGrom,10.139,40000000.0,594798.0,594798.0,TEX,TEX,2025.0,R,NaN,...,75.0,19.0,1.0,25.0,-1.234764,1.234764,-31.363,31.363,2025.0,R
5,Aaron Judge,8.051,40000000.0,592450.0,592450.0,NYY,NYY,2025.0,NaN,R,...,90.0,29.0,2.0,49.0,2.757520,-2.757520,70.041,-70.041,2025.0,R
6,Anthony Rendon,11.130,38571429.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
final_analysis_data["is_pitcher"] = final_analysis_data["position_perf"] == "P"
final_analysis_data = final_analysis_data.loc[:, ['Season', 'player_id', 'clean_name', 'position_perf', 'is_pitcher',
       'handedness', 'mls_years', 'salary_2025', 'TeamName', 'TeamNameAbb',
       'PA', 'AB', 'G', 'GS', 'IP', 'TBF', 'WAR', 'wRC+', 'OPS',
       'AVG', 'OBP', 'SLG', 'HR', 'RBI', 'SB', 'wOBA', 'xwOBA', 'ERA', 'FIP',
       'WHIP', 'K/9', 'BB/9', 'W', 'SV', 'xFIP', 'SIERA', 'wRAA', 'wRC',
       'FIP-', 'xFIP-', 'K-BB%', 'WHIP+', 'woba', 'xwoba', 'launch_speed',
       'launch_angle', 'hardhit_percent', 'barrels_per_bbe_percent',
       'velocity', 'spin_rate', 'effective_speed', 'release_extension', 'pa',
       'abs', 'pitches', 'hits', 'singles', 'doubles', 'triples', 'hrs',
       'batter_run_value_per_100', 'pitcher_run_value_per_100', 'run_exp',
       'pitcher_run_exp']]

final_analysis_data.rename(columns={'clean_name': 'player_name', "position_perf": "position"}, inplace=True)
df_final = final_analysis_data.loc[final_analysis_data.player_id.notna()].reset_index(drop=True)
df_final.head()

,Season,player_id,player_name,position,is_pitcher,handedness,mls_years,salary_2025,TeamName,TeamNameAbb,...,pitches,hits,singles,doubles,triples,hrs,batter_run_value_per_100,pitcher_run_value_per_100,run_exp,pitcher_run_exp
0,2025.0,665742.0,Juan Soto,OF,False,L,6.134,61875000.0,NYM,NYM,...,2869.0,148.0,85.0,20.0,1.0,42.0,2.103590,-2.103590,60.352,-60.352
1,2025.0,554430.0,Zack Wheeler,P,True,R,11.098,42000000.0,PHI,PHI,...,2394.0,107.0,65.0,21.0,2.0,19.0,-1.024394,1.024394,-24.524,24.524
2,2025.0,594798.0,Jacob deGrom,P,True,R,10.139,40000000.0,TEX,TEX,...,2540.0,120.0,75.0,19.0,1.0,25.0,-1.234764,1.234764,-31.363,31.363
3,2025.0,592450.0,Aaron Judge,OF,False,R,8.051,40000000.0,NYY,NYY,...,2540.0,170.0,90.0,29.0,2.0,49.0,2.757520,-2.757520,70.041,-70.041
4,2025.0,621043.0,Carlos Correa,SS,False,R,9.119,37333333.0,- - -,2 Tms,...,2217.0,143.0,103.0,27.0,0.0,13.0,-0.226613,0.226613,-5.024,5.024

In [18]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 64 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Season                     1059 non-null   float64
 1   player_id                  1059 non-null   float64
 2   player_name                1059 non-null   object
 3   position                   1059 non-null   object
 4   is_pitcher                 1059 non-null   bool
 5   handedness                 1059 non-null   object
 6   mls_years                  1059 non-null   float64
 7   salary_2025                863 non-null    float64
 8   TeamName                   1059 non-null   object
 9   TeamNameAbb                1059 non-null   object
 10  PA                         445 non-null    float64
 11  AB                         445 non-null    float64
 12  G                          1059 non-null   float64
 13  GS                         614 non-null    float64
 14  IP                         614 non-null    float64
 15  TBF                        614 non-null    float64
 16  WAR                        1059 non-null   float64
 17  wRC+                       445 non-null    float64
 18  OPS                        445 non-null    float64
 19  AVG                        1059 non-null   float64
 20  OBP                        445 non-null    float64
 21  SLG                        445 non-null    float64
 22  HR                         1059 non-null   float64
 23  RBI                        445 non-null    float64
 24  SB                         445 non-null    float64
 25  wOBA                       445 non-null    float64
 26  xwOBA                      445 non-null    float64
 27  ERA                        614 non-null    float64
 28  FIP                        614 non-null    float64
 29  WHIP                       614 non-null    float64
 30  K/9                        614 non-null    float64
 31  BB/9                       614 non-null    float64
 32  W                          614 non-null    float64
 33  SV                         614 non-null    float64
 34  xFIP                       614 non-null    float64
 35  SIERA                      614 non-null    float64
 36  wRAA                       445 non-null    float64
 37  wRC                        445 non-null    float64
 38  FIP-                       614 non-null    float64
 39  xFIP-                      614 non-null    float64
 40  K-BB%                      614 non-null    float64
 41  WHIP+                      614 non-null    float64
 42  woba                       1059 non-null   float64
 43  xwoba                      1059 non-null   float64
 44  launch_speed               1057 non-null   float64
 45  launch_angle               1057 non-null   float64
 46  hardhit_percent            1057 non-null   float64
 47  barrels_per_bbe_percent    1057 non-null   float64
 48  velocity                   1059 non-null   float64
 49  spin_rate                  1059 non-null   float64
 50  effective_speed            1059 non-null   float64
 51  release_extension          1059 non-null   float64
 52  pa                         1059 non-null   float64
 53  abs                        1059 non-null   float64
 54  pitches                    1059 non-null   float64
 55  hits                       1059 non-null   float64
 56  singles                    1059 non-null   float64
 57  doubles                    1059 non-null   float64
 58  triples                    1059 non-null   float64
 59  hrs                        1059 non-null   float64
 60  batter_run_value_per_100   1059 non-null   float64
 61  pitcher_run_value_per_100  1059 non-null   float64
 62  run_exp                    1059 non-null   float64
 63  pitcher_run_exp            1059 non-null   float64
dtypes: bool(1), float64(58), object(5)
memory usage: 522.4+ KB

In [19]:
df_final.TeamName.value_counts()

TeamName
- - -    121
DET       39
LAA       36
HOU       35
CIN       34
CHC       34
ATH       33
TEX       32
NYY       32
MIL       32
COL       32
SDP       32
CLE       32
BOS       31
CHW       31
ARI       31
WSN       31
ATL       31
PHI       31
SEA       31
TOR       31
KCR       30
TBR       30
NYM       30
SFG       29
BAL       29
MIA       29
PIT       29
STL       28
LAD       27
MIN       26
Name: count, dtype: int64

In [20]:
print(df_final.shape)
df_final.to_csv("baseball_salary_data_2025.csv", index=False)

(1059, 64)

In [23]:
pd.read_html("https://www.mlb.com/standings/mlb?tableType=regularSeasonExpanded")[0]

,TEAM,W,L,PCT,GB,WCGB,XTRA,1 RUN,DAY,NIGHT,GRASS,TURF,East,Central,West,AL/NL,VS. R,VS. L
0,Milwaukee Brewersy,95,61,0.609,-,-,7-4,28-19,35-29,60-32,90-54,5-7,21-9,30-19,16-13,28-20,66-44,29-17
1,Philadelphia Philliesy,92,64,0.590,3.0,-,8-5,24-20,29-27,63-37,82-58,10-6,29-20,14-16,20-12,29-16,70-39,22-25
2,Toronto Blue Jaysx,90,66,0.577,5.0,-,10-4,27-20,33-33,57-33,36-39,54-27,25-21,16-15,19-12,30-18,67-51,23-15
3,Chicago Cubsx,88,68,0.564,7.0,+8.0,6-5,25-19,39-31,49-37,83-61,5-7,14-13,27-22,17-15,30-18,69-46,19-22
4,Los Angeles Dodgersx,88,68,0.564,7.0,-,7-7,23-23,26-17,62-51,80-64,8-4,18-13,12-19,34-15,24-21,65-45,23-23
5,New York Yankees,88,68,0.564,7.0,+4.0,6-8,21-22,33-23,55-45,86-57,2-11,24-25,18-10,20-11,26-22,71-51,17-17
6,Seattle Mariners,87,69,0.558,8.0,-,10-11,30-21,33-20,54-49,81-63,6-6,10-20,21-11,34-18,22-20,60-50,27-19
7,Boston Red Sox,85,71,0.545,10.0,+1.0,8-12,21-26,31-23,54-48,82-64,3-7,30-19,15-13,14-17,26-22,61-50,24-21
8,Detroit Tigers,85,71,0.545,10.0,-,5-8,20-10,36-27,49-44,81-66,4-5,18-10,29-20,15-16,23-25,62-55,23-16
9,San Diego Padres,85,71,0.545,10.0,+5.0,7-4,29-23,32-23,53-48,81-63,4-8,20-11,16-12,29-20,20-28,61-48,24-23
10,Cleveland Guardians,84,72,0.538,11.0,-,11-6,24-20,27-27,57-45,81-66,3-6,17-15,34-15,13-14,20-28,65-48,19-24
11,Houston Astros,84,72,0.538,11.0,-,8-7,27-16,27-23,57-49,75-65,9-7,16-16,15-15,22-24,31-17,66-59,18-13
12,Cincinnati Reds,80,76,0.513,15.0,-,3-11,21-21,33-23,47-53,78-71,2-5,14-18,23-23,17-13,26-22,60-51,20-25
13,New York Mets,80,76,0.513,15.0,-,6-7,23-26,29-32,51-44,76-74,4-2,24-25,13-15,19-12,24-24,56-55,24-21
14,Arizona Diamondbacks,79,77,0.506,16.0,1.0,7-11,20-27,28-25,51-52,31-38,48-39,15-15,14-18,25-21,25-23,58-54,21-23
15,Texas Rangers,79,77,0.506,16.0,5.0,9-7,21-27,25-25,54-52,30-42,49-35,15-16,14-11,25-27,25-23,62-55,17-22
16,Kansas City Royals,78,78,0.500,17.0,6.0,7-5,24-18,29-27,49-51,70-74,8-4,13-17,26-26,13-13,26-22,61-66,17-12
17,San Francisco Giants,77,79,0.494,18.0,3.0,9-6,26-28,32-33,45-46,72-71,5-8,16-15,16-12,21-28,24-24,61-51,16-28
18,Miami Marlins,76,80,0.487,19.0,4.0,9-4,21-21,37-29,39-51,34-38,42-42,20-26,16-16,14-16,26-22,57-55,19-25
19,St. Louis Cardinals,76,80,0.487,19.0,4.0,4-8,24-20,30-32,46-48,73-74,3-6,16-15,24-25,14-14,22-26,52-58,24-22
20,Tampa Bay Rays,76,80,0.487,19.0,8.0,5-7,22-28,30-28,46-52,71-73,5-7,19-27,13-18,16-15,28-20,56-54,20-26
21,Athletics,73,83,0.468,22.0,11.0,9-5,19-21,22-27,51-56,68-74,5-9,14-17,18-10,21-28,20-28,53-67,20-16
22,Atlanta Braves,73,83,0.468,22.0,7.0,8-8,20-34,20-26,53-57,66-74,7-9,28-21,14-14,9-22,22-26,51-64,22-19
23,Baltimore Orioles,73,83,0.468,22.0,11.0,6-6,26-23,34-32,39-51,69-74,4-9,20-26,12-19,17-14,24-24,51-58,22-25
24,Los Angeles Angels,70,86,0.449,25.0,14.0,9-5,26-21,16-28,54-58,69-78,1-8,14-17,12-16,22-27,22-26,59-70,11-16
25,Minnesota Twins,67,89,0.429,28.0,17.0,4-10,15-26,28-38,39-51,65-85,2-4,16-14,20-32,12-17,19-26,56-67,11-22
26,Pittsburgh Pirates,67,89,0.429,28.0,13.0,6-7,24-34,28-38,39-51,64-85,3-4,16-13,17-32,17-13,17-31,53-69,14-20
27,Washington Nationals,64,92,0.410,31.0,16.0,5-3,22-16,26-43,38-49,59-84,5-8,20-29,11-20,15-16,18-27,47-63,17-29
28,Chicago White Sox,58,98,0.372,37.0,26.0,3-7,14-34,26-42,32-56,56-94,2-4,11-18,18-34,10-20,19-26,43-77,15-21
29,Colorado Rockies,43,113,0.276,52.0,37.0,1-5,18-21,19-42,24-71,39-105,4-8,9-23,10-20,12-37,12-33,35-79,8-34

In [26]:
df_final.TeamNameAbb.unique()

array(['NYM', 'PHI', 'TEX', 'NYY', '2 Tms', 'LAA', 'HOU', 'LAD', 'TOR',
       'CHC', 'COL', 'SDP', 'SFG', 'DET', 'SEA', 'BOS', 'ATL', 'KCR',
       'MIN', 'CIN', 'ARI', 'ATH', 'CLE', 'STL', 'BAL', 'MIL', 'MIA',
       'CHW', 'PIT', '3 Tms', 'TBR', 'WSN'], dtype=object)